### ISSUE TITLE
页面刷新问题

### ISSUE THREAD

**Issue by yjxandroid** [zhongbaitu/WaveLoadingView#1]
你好，我看了一下源码 ，没有发现在哪儿刷新页面的！ 请问你是在哪儿刷新页面的？

**Comment by zhongbaitu** [comment]
@yjxandroid 你好，是我在`onDraw`调用了`setBackgroundDrawable`方法，`setBackgroundDrawable`里面有用`invalidate`刷新，这样的话就相当于在`onDraw`调用`invalidate`的效果是一样的。

这个问题其实你不问，我也没察觉。只是当时看到效果了就没检查太多，这样写的确很含糊，谢谢提醒。
