### ISSUE TITLE
延迟启动问题

### ISSUE THREAD

**Issue by lwtor** [zhongbaitu/WaveLoadingView#2]
为什么需要延迟两秒再启动，而且直接启动的话，界面就不会刷新了

**Comment by zhongbaitu** [comment]
@lwtor 你说延迟两秒再启动是什么意思？ 可以贴下代码吗

**Comment by lwtor** [comment]
@zhongbaitu 
 你的代码中写的是
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mWaveLoadingView.updateProgress(0.8f);
                Log.e("MainActivity", "start wave");
            }
        }, 2000);
我改成handler().post()或者把2000改成100的话，就不行了

**Comment by zhongbaitu** [comment]
@lwtor 因为mWaveLoadingView还没完成绘制（甚至还没完成测量），这个时候，mWaveLoadingView是不工作的。
